[package]
name = "Rust-Project"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
petgraph = "0.8.0"
ndarray = "0.16.0"
ndarray-stats = "0.6.0"
linfa = "0.7"
linfa-linear = "0.7"
linfa-trees = "0.7"